### ISSUE TITLE
the crs initialisation in your demo is depricated

### ISSUE THREAD

**Issue by clive3** [BritishGeologicalSurvey/geopandas-demo#6]
so that:

countries_osgb = countries.to_crs({'init': 'epsg:27700'}) 

becomes:

countries_osgb = countries.to_crs('epsg:27700')

**Comment by volcan01010** [comment]
Thanks @clive3, I'd noticed this before but never merged the fix.  This issue was a good nudge to do it now.

**Comment by clive3** [comment]
no problem - I like your tutorial - very useful intro to geopandas for me right now
best- Clive
    On Thursday, 7 May 2020, 23:24:23 BST, John A Stevenson <notifications@github.com> wrote:  
 
 


Thanks @clive3, I'd noticed this before but never merged the fix. This issue was a good nudge to do it now.
